# Generated by Django 2.0 on 2022-03-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220303_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nomeMarca',
            new_name='nome',
        ),
    ]
